on: push
jobs:
  conda:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda activate PGE310
      - name: Install Nikola
        shell: bash -l {0}
        run: |
          pip install markdown==2.6.6
          pip install nikola==7.7.12
      - name: Build Site
        shell: bash -l {0}
        run: nikola build
      - name: Deploy to Github 
        shell: bash -l {0}
        run: nikola github_deploy
